In [1]:
import sys
import json
import csv 
import os
import pandas as pd

In [2]:
raw_loc = os.path.join('..','RawData')
clean_loc = os.path.join('..','CleanData')

In [3]:
big_geojson = os.path.join(raw_loc,'US_HistCounties_Gen05.json')
big_geojson

'..\\RawData\\US_HistCounties_Gen05.json'

In [4]:
# use 1982 as a test year
year2find = 1982

# create a reference to the output file
outfile = os.path.join(raw_loc,f'Test_GeoFile{year2find}.json')

# Create a blank list of the features we will keep
features = []

# initialize a count of all records on the big geojson file
geojson_count = 0

# Open up the existing geojson file and read it into the empty geojson dictionary created above.
# While reading it in, pull the matching state and county fips from the empdata dictionary so we can add the unemployment info to the geojson.
with open(big_geojson, 'r') as f:
    temp = json.load(f)
    
    for feature in temp['features']:
        geojson_count = geojson_count + 1
        featureProperties = feature['properties']
        fips = featureProperties['FIPS']
        start_year = int(featureProperties["START_DATE"][0:4])
        end_year = int(featureProperties["END_DATE"][0:4])
        
        if start_year <= year2find and year2find <= end_year:
            features.append(feature)

print(f"Records read from large geojson file: {geojson_count}")
print(f"Records that were kept: {len(features)}")

# Output a new geojson file specific to this year.
with open(outfile,'w') as f:
    f.write('{"type":"FeatureCollection","features": [')
    for feature in features:
        json.dump(feature, f)
        f.write(',\n')
    f.write(']}')

Records read from large geojson file: 17727
Records that were kept: 3142

In [5]:
xlsfile = os.path.join(raw_loc,'GeoFRED_Per_Capita_Personal_Income_by_County_Dollars2.xls')
xl = pd.ExcelFile(xlsfile)
pcpi = xl.parse('Sheet0')
cols_in = pcpi.columns
cols_rename = []

for col in cols_in:
    if col == 'Region Code':
        cols_rename.append('FIPS')
    elif col in ('Series ID','Region Name'):
        cols_rename.append('DROP')
    elif int(col) >= 2001:
        cols_rename.append(f"PCPI_{col}")
    else:
        cols_rename.append('DROP')

pcpi.columns = cols_rename
pcpi.drop(columns =['DROP'], inplace = True) 
pcpi["In PCPI"] = 1

# Make sure the fips codes have leading zeros.
for obs in range(0,len(pcpi)):
    if len(str(pcpi.loc[obs,'FIPS'])) == 4:
        pcpi.loc[obs,'FIPS'] = f"0{pcpi.loc[obs,'FIPS']}"
    else:
        pcpi.loc[obs,'FIPS'] = f"{pcpi.loc[obs,'FIPS']}"
        
    # 46113 was renamed from Shannon County to Oglala Lakota County, SD in May 2015.  Oglala should have FIPS 46102 but
    # 46102 is not found on the big geojson file so we reset 46102 to 46113.
    if str(pcpi.loc[obs,'FIPS']) == '46102':
        pcpi.loc[obs,'FIPS'] = '46113'

pcpi.head()

,FIPS,PCPI_2001,PCPI_2002,PCPI_2003,PCPI_2004,PCPI_2005,PCPI_2006,PCPI_2007,PCPI_2008,PCPI_2009,PCPI_2010,PCPI_2011,PCPI_2012,PCPI_2013,PCPI_2014,PCPI_2015,PCPI_2016,PCPI_2017,In PCPI
0,45001,23201.0,21528.0,20359.0,21756.0,22375.0,23410.0,24311.0,25712.0,25702,26619,27675,27555,28193,29498.0,30928.0,31785.0,33044.0,1
1,22001,21019.0,21565.0,22264.0,22569.0,24134.0,25908.0,27751.0,31483.0,31140,31569,32797,34456,36229,37336.0,35676.0,34158.0,35401.0,1
2,51001,21119.0,22156.0,23971.0,25337.0,26630.0,27828.0,29914.0,32114.0,32607,33556,33989,35525,36069,37225.0,38807.0,39099.0,40701.0,1
3,16001,33528.0,34195.0,34676.0,36657.0,37544.0,40471.0,40561.0,39479.0,37727,38275,39649,41472,42857,45259.0,47671.0,48419.0,49900.0,1
4,29001,21125.0,21065.0,21269.0,22361.0,23133.0,24114.0,25295.0,26552.0,27800,27158,28405,28618,29215,30036.0,31139.0,31186.0,32037.0,1

In [6]:
xlsfile = os.path.join(raw_loc,'GeoFRED_Unemployment_Rate_by_County_Percent2.xls')
xl = pd.ExcelFile(xlsfile)
df0 = xl.parse('Sheet0')
df0.drop(columns =['Series ID'], inplace = True) 
df0.head()

,Region Name,Region Code,1976 January,1976 February,1976 March,1976 April,1976 May,1976 June,1976 July,1976 August,...,1996 April,1996 May,1996 June,1996 July,1996 August,1996 September,1996 October,1996 November,1996 December,1997 January
0,"Abbeville County, SC",45001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,6.6,7.2,9.3,6.7,5.8,5.9,5.5,5.3,6.2
1,"Acadia Parish, LA",22001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.5,7.6,7.9,6.9,6.7,6.8,6.4,6.2,5.6,6.1
2,"Accomack County, VA",51001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.4,8.4,8.3,7.2,7.6,7.9,7.5,9.6,10.3,14.0
3,"Ada County, ID",16001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.4,3.0,3.3,3.2,3.1,3.2,3.3,3.2,3.0,3.8
4,"Adair County, IA",19001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9,3.4,3.1,2.8,2.6,2.8,2.6,2.2,2.6,4.2

In [7]:
df1 = xl.parse('Sheet1')
df1.drop(columns =['Series ID','Region Name'], inplace = True) 
df1.head()

,Region Code,1997 February,1997 March,1997 April,1997 May,1997 June,1997 July,1997 August,1997 September,1997 October,...,2017 May,2017 June,2017 July,2017 August,2017 September,2017 October,2017 November,2017 December,2018 January,2018 February
0,45001,9.8,9.0,8.5,8.3,6.4,7.4,7.4,4.4,4.0,...,4.1,4.9,5.4,5.2,4.5,4.3,4.2,4.3,5.1,4.3
1,22001,4.9,5.2,5.1,4.9,6.2,5.7,8.9,9.3,4.8,...,5.9,6.6,6.2,6.2,5.7,5.1,4.9,4.6,5.5,5.0
2,51001,13.6,12.7,10.0,8.8,9.6,6.4,6.9,6.8,6.2,...,4.1,4.0,4.1,4.3,3.9,3.9,3.9,4.5,5.2,5.2
3,16001,3.6,3.3,3.0,2.6,2.9,2.9,2.9,3.0,3.0,...,2.6,2.7,2.7,2.6,2.5,2.4,2.7,2.6,3.3,3.1
4,19001,3.9,3.4,3.1,2.3,2.6,2.2,2.3,2.4,2.1,...,2.5,2.5,2.3,2.5,2.5,2.0,2.0,2.7,3.6,3.7

In [8]:
df2 = xl.parse('Sheet2')
df2.drop(columns =['Series ID','Region Name'], inplace = True) 
df2.head()

,Region Code,2018 March,2018 April,2018 May,2018 June,2018 July,2018 August,2018 September,2018 October,2018 November,2018 December,2019 January,2019 February,2019 March,2019 April,2019 May,2019 June,2019 July
0,45001,3.9,3.1,3.3,4.4,4.3,4.3,3.9,3.9,3.5,3.8,4.4,3.6,3.8,3.3,3.9,4.2,3.8
1,22001,5.1,4.9,5.2,6.7,6.1,5.8,5.4,5.0,4.8,4.8,5.7,4.8,4.2,3.9,4.6,5.8,5.5
2,51001,4.6,3.5,3.4,3.6,3.5,3.6,3.2,3.1,3.1,3.8,5.1,4.8,4.0,3.3,3.3,3.2,3.1
3,16001,2.9,2.5,2.2,2.3,2.3,2.2,2.1,2.1,2.3,2.4,3.3,2.9,2.7,2.2,2.1,2.4,2.5
4,19001,3.0,2.6,2.0,2.2,2.0,2.1,1.9,1.7,1.7,2.1,2.9,2.9,2.7,2.0,1.9,2.1,2.1

In [9]:
unemp = pd.merge(df0,pd.merge(df1,df2,on='Region Code'),on='Region Code')
unemp.head()

,Region Name,Region Code,1976 January,1976 February,1976 March,1976 April,1976 May,1976 June,1976 July,1976 August,...,2018 October,2018 November,2018 December,2019 January,2019 February,2019 March,2019 April,2019 May,2019 June,2019 July
0,"Abbeville County, SC",45001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9,3.5,3.8,4.4,3.6,3.8,3.3,3.9,4.2,3.8
1,"Acadia Parish, LA",22001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,4.8,4.8,5.7,4.8,4.2,3.9,4.6,5.8,5.5
2,"Accomack County, VA",51001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.1,3.1,3.8,5.1,4.8,4.0,3.3,3.3,3.2,3.1
3,"Ada County, ID",16001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.1,2.3,2.4,3.3,2.9,2.7,2.2,2.1,2.4,2.5
4,"Adair County, IA",19001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.7,1.7,2.1,2.9,2.9,2.7,2.0,1.9,2.1,2.1

In [10]:
cols_in = unemp.columns
print('Original Column Names:')
print(cols_in)
cols_rename = []

for col in cols_in:
    
    if col == 'Region Code':
        cols_rename.append('FIPS')
    elif col in ('Series ID','Region Name') or col[0:3] in ('198','197'):
        cols_rename.append('DROP')
    elif "January" in col:
        cols_rename.append(f"Unemp_{col[0:4]}01")
    elif "February" in col:
        cols_rename.append(f"Unemp_{col[0:4]}02")
    elif "March" in col:
        cols_rename.append(f"Unemp_{col[0:4]}03")
    elif "April" in col:
        cols_rename.append(f"Unemp_{col[0:4]}04")
    elif "May" in col:
        cols_rename.append(f"Unemp_{col[0:4]}05")
    elif "June" in col:
        cols_rename.append(f"Unemp_{col[0:4]}06")
    elif "July" in col:
        cols_rename.append(f"Unemp_{col[0:4]}07")
    elif "August" in col:
        cols_rename.append(f"Unemp_{col[0:4]}08")
    elif "September" in col:
        cols_rename.append(f"Unemp_{col[0:4]}09")
    elif "October" in col:
        cols_rename.append(f"Unemp_{col[0:4]}10")
    elif "November" in col:
        cols_rename.append(f"Unemp_{col[0:4]}11")
    elif "December" in col:
        cols_rename.append(f"Unemp_{col[0:4]}12")
    else:
        cols_rename.append(col)

print('Renamed Column Names:')
print(cols_rename)

# Reset the column names
unemp.columns = cols_rename

# Get rid of dropped columns
unemp.drop(columns =['DROP'], inplace = True) 
unemp["In Unemp"] = 1


# Make sure the fips codes have leading zeros.
for obs in range(0,len(unemp)):
    if len(str(unemp.loc[obs,'FIPS'])) == 4:
        unemp.loc[obs,'FIPS'] = f"0{unemp.loc[obs,'FIPS']}"
    else:
        unemp.loc[obs,'FIPS'] = f"{unemp.loc[obs,'FIPS']}"
        
    # 46113 was renamed from Shannon County to Oglala Lakota County, SD in May 2015.  Oglala should have FIPS 46102 but
    # 46102 is not found on the big geojson file so we reset 46102 to 46113.
    if str(unemp.loc[obs,'FIPS']) == '46102':
        unemp.loc[obs,'FIPS'] = '46113'

unemp.head()

Original Column Names:
Index(['Region Name', 'Region Code', '1976 January', '1976 February',
       '1976 March', '1976 April', '1976 May', '1976 June', '1976 July',
       '1976 August',
       ...
       '2018 October', '2018 November', '2018 December', '2019 January',
       '2019 February', '2019 March', '2019 April', '2019 May', '2019 June',
       '2019 July'],
      dtype='object', length=525)
Renamed Column Names:
['DROP', 'FIPS', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'Unemp_199001', 'Unemp_199002', 'Unemp_199003', 'Unemp_199004', 'Unemp_199005', 'Unemp_199006', 'Unemp_199007', 'Unemp_199008', 'Unemp_199009', 'Unemp_199010', 'Unemp_199011', 'Unemp_199012', 'Unemp_199101', 'Unemp_199102', 'Unemp_199103', 'Unemp_199104', 'Unemp_199105', 'Unemp_199106', 'Unemp_199107', 'Unemp_199108', 'Unemp_199109', 'Unemp_199110', 'Unemp_199111', 'Unemp_199112', 'Unemp_199201', 'Unemp_199202', 'Unemp_199203', 'Unemp_199204', 'Unemp_199205', 'Unemp_199206', 'Unemp_199207', 'Unemp_199208', 'Unemp_199209', 'Unemp_199210', 'Unemp_199211', 'Unemp_199212', 'Unemp_199301', 'Unemp_199302', 'Unemp_199303', 'Unemp_199304', 'Unemp_199305', 'Unemp_199306', 'Unemp_199307', 'Unemp_199308', 'Unemp_199309', 'Unemp_199310', 'Unemp_199311', 'Unemp_199312', 'Unemp_199401', 'Unemp_199402', 'Unemp_199403', 'Unemp_199404', 'Unemp_199405', 'Unemp_199406', 'Unemp_199407', 'Unemp_199408', 'Unemp_199409', 'Unemp_199410', 'Unemp_199411', 'Unemp_199412', 'Unemp_199501', 'Unemp_199502', 'Unemp_199503', 'Unemp_199504', 'Unemp_199505', 'Unemp_199506', 'Unemp_199507', 'Unemp_199508', 'Unemp_199509', 'Unemp_199510', 'Unemp_199511', 'Unemp_199512', 'Unemp_199601', 'Unemp_199602', 'Unemp_199603', 'Unemp_199604', 'Unemp_199605', 'Unemp_199606', 'Unemp_199607', 'Unemp_199608', 'Unemp_199609', 'Unemp_199610', 'Unemp_199611', 'Unemp_199612', 'Unemp_199701', 'Unemp_199702', 'Unemp_199703', 'Unemp_199704', 'Unemp_199705', 'Unemp_199706', 'Unemp_199707', 'Unemp_199708', 'Unemp_199709', 'Unemp_199710', 'Unemp_199711', 'Unemp_199712', 'Unemp_199801', 'Unemp_199802', 'Unemp_199803', 'Unemp_199804', 'Unemp_199805', 'Unemp_199806', 'Unemp_199807', 'Unemp_199808', 'Unemp_199809', 'Unemp_199810', 'Unemp_199811', 'Unemp_199812', 'Unemp_199901', 'Unemp_199902', 'Unemp_199903', 'Unemp_199904', 'Unemp_199905', 'Unemp_199906', 'Unemp_199907', 'Unemp_199908', 'Unemp_199909', 'Unemp_199910', 'Unemp_199911', 'Unemp_199912', 'Unemp_200001', 'Unemp_200002', 'Unemp_200003', 'Unemp_200004', 'Unemp_200005', 'Unemp_200006', 'Unemp_200007', 'Unemp_200008', 'Unemp_200009', 'Unemp_200010', 'Unemp_200011', 'Unemp_200012', 'Unemp_200101', 'Unemp_200102', 'Unemp_200103', 'Unemp_200104', 'Unemp_200105', 'Unemp_200106', 'Unemp_200107', 'Unemp_200108', 'Unemp_200109', 'Unemp_200110', 'Unemp_200111', 'Unemp_200112', 'Unemp_200201', 'Unemp_200202', 'Unemp_200203', 'Unemp_200204', 'Unemp_200205', 'Unemp_200206', 'Unemp_200207', 'Unemp_200208', 'Unemp_200209', 'Unemp_200210', 'Unemp_200211', 'Unemp_200212', 'Unemp_200301', 'Unemp_200302', 'Unemp_200303', 'Unemp_200304', 'Unemp_200305', 'Unemp_200306', 'Unemp_200307', 'Unemp_200308', 'Unemp_200309', 'Unemp_200310', 'Unemp_200311', 'Unemp_200312', 'Unemp_200401', 'Unemp_200402', 'Unemp_200403', 'Unemp_200404', 'Unemp_200405', 'Unemp_200406', 'Unemp_200407', 'Unemp_200408', 'Unemp_200409', 'Unemp_200410', 'Unemp_200411', 'Unemp_200412', 'Unemp_200501', 'Unemp_200502', 'Unemp_200503', 'Unemp_200504', 'Unemp_200505', 'Unemp_200506', 'Unemp_200507', 'Unemp_200508', 'Unemp_200509', 'Unemp_200510', 'Unemp_200511', 'Unemp_200512', 'Unemp_200601', 'Unemp_200602', 'Unemp_200603', 'Unemp_200604', 'Unemp_200605', 'Unemp_200606', 'Unemp_200607', 'Unemp_200608', 'Unemp_200609', 'Unemp_200610', 'Unemp_200611', 'Unemp_200612', 'Unemp_200701', 'Unemp_200702', 'Unemp_200703', 'Unemp_200704', 'Unemp_200705', 'Unemp_200706', 'Unemp_200707', 'Unemp_200708', 'Unemp_200709', 'Unemp_200710', 'Unemp_200711', 'Unemp_200712', 'Unemp_200801', 'Unemp_200802', 'Unemp_200803', 'Unemp_200804', 'Unemp_200805', 'Unemp_200806', 'Unemp_200807', 'Unemp_200808', 'Unemp_200809', 'Unemp_200810', 'Unemp_200811', 'Unemp_200812', 'Unemp_200901', 'Unemp_200902', 'Unemp_200903', 'Unemp_200904', 'Unemp_200905', 'Unemp_200906', 'Unemp_200907', 'Unemp_200908', 'Unemp_200909', 'Unemp_200910', 'Unemp_200911', 'Unemp_200912', 'Unemp_201001', 'Unemp_201002', 'Unemp_201003', 'Unemp_201004', 'Unemp_201005', 'Unemp_201006', 'Unemp_201007', 'Unemp_201008', 'Unemp_201009', 'Unemp_201010', 'Unemp_201011', 'Unemp_201012', 'Unemp_201101', 'Unemp_201102', 'Unemp_201103', 'Unemp_201104', 'Unemp_201105', 'Unemp_201106', 'Unemp_201107', 'Unemp_201108', 'Unemp_201109', 'Unemp_201110', 'Unemp_201111', 'Unemp_201112', 'Unemp_201201', 'Unemp_201202', 'Unemp_201203', 'Unemp_201204', 'Unemp_201205', 'Unemp_201206', 'Unemp_201207', 'Unemp_201208', 'Unemp_201209', 'Unemp_201210', 'Unemp_201211', 'Unemp_201212', 'Unemp_201301', 'Unemp_201302', 'Unemp_201303', 'Unemp_201304', 'Unemp_201305', 'Unemp_201306', 'Unemp_201307', 'Unemp_201308', 'Unemp_201309', 'Unemp_201310', 'Unemp_201311', 'Unemp_201312', 'Unemp_201401', 'Unemp_201402', 'Unemp_201403', 'Unemp_201404', 'Unemp_201405', 'Unemp_201406', 'Unemp_201407', 'Unemp_201408', 'Unemp_201409', 'Unemp_201410', 'Unemp_201411', 'Unemp_201412', 'Unemp_201501', 'Unemp_201502', 'Unemp_201503', 'Unemp_201504', 'Unemp_201505', 'Unemp_201506', 'Unemp_201507', 'Unemp_201508', 'Unemp_201509', 'Unemp_201510', 'Unemp_201511', 'Unemp_201512', 'Unemp_201601', 'Unemp_201602', 'Unemp_201603', 'Unemp_201604', 'Unemp_201605', 'Unemp_201606', 'Unemp_201607', 'Unemp_201608', 'Unemp_201609', 'Unemp_201610', 'Unemp_201611', 'Unemp_201612', 'Unemp_201701', 'Unemp_201702', 'Unemp_201703', 'Unemp_201704', 'Unemp_201705', 'Unemp_201706', 'Unemp_201707', 'Unemp_201708', 'Unemp_201709', 'Unemp_201710', 'Unemp_201711', 'Unemp_201712', 'Unemp_201801', 'Unemp_201802', 'Unemp_201803', 'Unemp_201804', 'Unemp_201805', 'Unemp_201806', 'Unemp_201807', 'Unemp_201808', 'Unemp_201809', 'Unemp_201810', 'Unemp_201811', 'Unemp_201812', 'Unemp_201901', 'Unemp_201902', 'Unemp_201903', 'Unemp_201904', 'Unemp_201905', 'Unemp_201906', 'Unemp_201907']

,FIPS,Unemp_199001,Unemp_199002,Unemp_199003,Unemp_199004,Unemp_199005,Unemp_199006,Unemp_199007,Unemp_199008,Unemp_199009,...,Unemp_201811,Unemp_201812,Unemp_201901,Unemp_201902,Unemp_201903,Unemp_201904,Unemp_201905,Unemp_201906,Unemp_201907,In Unemp
0,45001,7.0,6.8,6.8,5.5,5.5,6.4,9.3,6.4,5.7,...,3.5,3.8,4.4,3.6,3.8,3.3,3.9,4.2,3.8,1
1,22001,5.7,5.1,5.1,4.8,5.6,7.1,9.6,8.1,7.3,...,4.8,4.8,5.7,4.8,4.2,3.9,4.6,5.8,5.5,1
2,51001,8.3,8.1,6.7,5.4,4.4,3.7,3.1,5.2,5.0,...,3.1,3.8,5.1,4.8,4.0,3.3,3.3,3.2,3.1,1
3,16001,4.5,4.5,3.9,3.3,3.2,3.6,3.2,3.2,3.6,...,2.3,2.4,3.3,2.9,2.7,2.2,2.1,2.4,2.5,1
4,19001,4.0,3.7,3.3,2.5,1.6,1.9,1.9,2.1,1.8,...,1.7,2.1,2.9,2.9,2.7,2.0,1.9,2.1,2.1,1

In [11]:
xlsfile = os.path.join(raw_loc,'EducationByCounty2.xls')
xl = pd.ExcelFile(xlsfile)
edu = xl.parse('Education 1970 to 2017')
cols_in = edu.columns

print('Original Column Names:')
print(cols_in)
cols_rename = []

cols_in

for col in cols_in:
    if col == 'FIPS Code':
        cols_rename.append('FIPS')  
    elif col == 'State':
        cols_rename.append('State Abbr')  
    elif col == 'Area name':
        cols_rename.append('County Name')  

    elif col == 'Percent of adults with less than a high school diploma, 1970':
        cols_rename.append('1970_LTHS')
    elif col == 'Percent of adults with a high school diploma only, 1970':
        cols_rename.append('1970_HS')
    elif col == 'Percent of adults completing some college (1-3 years), 1970':
        cols_rename.append('1970_SomeColl')
    elif col == 'Percent of adults completing four years of college or higher, 1970':
        cols_rename.append('1970_GRAD')

    elif col == 'Percent of adults with less than a high school diploma, 1980':
        cols_rename.append('1980_LTHS')
    elif col == 'Percent of adults with a high school diploma only, 1980':
        cols_rename.append('1980_HS')
    elif col == 'Percent of adults completing some college (1-3 years), 1980':
        cols_rename.append('1980_SomeColl')
    elif col == 'Percent of adults completing four years of college or higher, 1980':
        cols_rename.append('1980_GRAD')
        
    elif col == 'Percent of adults with less than a high school diploma, 1990':
        cols_rename.append('1990_LTHS')
    elif col == 'Percent of adults with a high school diploma only, 1990':
        cols_rename.append('1990_HS')
    elif col == "Percent of adults completing some college or associate's degree, 1990":
        cols_rename.append('1990_SomeColl')
    elif col == "Percent of adults with a bachelor's degree or higher, 1990":
        cols_rename.append('1990_GRAD')        

    elif col == 'Percent of adults with less than a high school diploma, 2000':
        cols_rename.append('2000_LTHS')
    elif col == 'Percent of adults with a high school diploma only, 2000':
        cols_rename.append('2000_HS')
    elif col == "Percent of adults completing some college or associate's degree, 2000":
        cols_rename.append('2000_SomeColl')
    elif col == "Percent of adults with a bachelor's degree or higher, 2000":
        cols_rename.append('2000_GRAD')        

    elif col == 'Percent of adults with less than a high school diploma, 2013-17':
        cols_rename.append('2013_LTHS')
    elif col == 'Percent of adults with a high school diploma only, 2013-17':
        cols_rename.append('2013_HS')
    elif col == "Percent of adults completing some college or associate's degree, 2013-17":
        cols_rename.append('2013_SomeColl')
    elif col == "Percent of adults with a bachelor's degree or higher, 2013-17":
        cols_rename.append('2013_GRAD')        
        
    else:
        cols_rename.append('DROP')


print('Renamed Column Names:')
print(cols_rename)
        
edu.columns = cols_rename
edu.drop(columns =['DROP'], inplace = True) 
edu["In Edu"] = 1

# Make sure the fips codes have leading zeros.
for obs in range(0,len(edu)):
    if len(str(edu.loc[obs,'FIPS'])) == 4:
        edu.loc[obs,'FIPS'] = f"0{edu.loc[obs,'FIPS']}"
    else:
        edu.loc[obs,'FIPS'] = f"{edu.loc[obs,'FIPS']}"
        
    # FIPS code 0 for nation or last 3 digit 000 indicate state total
    if len(str(edu.loc[obs,'FIPS'])) == 1:
        edu.loc[obs,'FIPS'] = "DROP"
    elif edu.loc[obs,'FIPS'][2:5] == '000':
        edu.loc[obs,'FIPS'] = "DROP"

    # 46113 was renamed from Shannon County to Oglala Lakota County, SD in May 2015.  Oglala should have FIPS 46102 but
    # 46102 is not found on the big geojson file so we reset 46102 to 46113.
    if str(edu.loc[obs,'FIPS']) == '46102':
        edu.loc[obs,'FIPS'] = '46113'

# Drop state and national total lines
edu = edu.loc[edu["FIPS"] != 'DROP',:]

print('Final Column Names:')
print(edu.columns)

edu.head()

Original Column Names:
Index(['FIPS Code', 'State', 'Area name', '2003 Rural-urban Continuum Code',
       '2003 Urban Influence Code', '2013 Rural-urban Continuum Code',
       '2013 Urban Influence Code', 'Less than a high school diploma, 1970',
       'High school diploma only, 1970', 'Some college (1-3 years), 1970',
       'Four years of college or higher, 1970',
       'Percent of adults with less than a high school diploma, 1970',
       'Percent of adults with a high school diploma only, 1970',
       'Percent of adults completing some college (1-3 years), 1970',
       'Percent of adults completing four years of college or higher, 1970',
       'Less than a high school diploma, 1980',
       'High school diploma only, 1980', 'Some college (1-3 years), 1980',
       'Four years of college or higher, 1980',
       'Percent of adults with less than a high school diploma, 1980',
       'Percent of adults with a high school diploma only, 1980',
       'Percent of adults completing some college (1-3 years), 1980',
       'Percent of adults completing four years of college or higher, 1980',
       'Less than a high school diploma, 1990',
       'High school diploma only, 1990',
       'Some college or associate's degree, 1990',
       'Bachelor's degree or higher, 1990',
       'Percent of adults with less than a high school diploma, 1990',
       'Percent of adults with a high school diploma only, 1990',
       'Percent of adults completing some college or associate's degree, 1990',
       'Percent of adults with a bachelor's degree or higher, 1990',
       'Less than a high school diploma, 2000',
       'High school diploma only, 2000',
       'Some college or associate's degree, 2000',
       'Bachelor's degree or higher, 2000',
       'Percent of adults with less than a high school diploma, 2000',
       'Percent of adults with a high school diploma only, 2000',
       'Percent of adults completing some college or associate's degree, 2000',
       'Percent of adults with a bachelor's degree or higher, 2000',
       'Less than a high school diploma, 2013-17',
       'High school diploma only, 2013-17',
       'Some college or associate's degree, 2013-17',
       'Bachelor's degree or higher, 2013-17',
       'Percent of adults with less than a high school diploma, 2013-17',
       'Percent of adults with a high school diploma only, 2013-17',
       'Percent of adults completing some college or associate's degree, 2013-17',
       'Percent of adults with a bachelor's degree or higher, 2013-17'],
      dtype='object')
Renamed Column Names:
['FIPS', 'State Abbr', 'County Name', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', 'DROP', '1970_LTHS', '1970_HS', '1970_SomeColl', '1970_GRAD', 'DROP', 'DROP', 'DROP', 'DROP', '1980_LTHS', '1980_HS', '1980_SomeColl', '1980_GRAD', 'DROP', 'DROP', 'DROP', 'DROP', '1990_LTHS', '1990_HS', '1990_SomeColl', '1990_GRAD', 'DROP', 'DROP', 'DROP', 'DROP', '2000_LTHS', '2000_HS', '2000_SomeColl', '2000_GRAD', 'DROP', 'DROP', 'DROP', 'DROP', '2013_LTHS', '2013_HS', '2013_SomeColl', '2013_GRAD']
Final Column Names:
Index(['FIPS', 'State Abbr', 'County Name', '1970_LTHS', '1970_HS',
       '1970_SomeColl', '1970_GRAD', '1980_LTHS', '1980_HS', '1980_SomeColl',
       '1980_GRAD', '1990_LTHS', '1990_HS', '1990_SomeColl', '1990_GRAD',
       '2000_LTHS', '2000_HS', '2000_SomeColl', '2000_GRAD', '2013_LTHS',
       '2013_HS', '2013_SomeColl', '2013_GRAD', 'In Edu'],
      dtype='object')

,FIPS,State Abbr,County Name,1970_LTHS,1970_HS,1970_SomeColl,1970_GRAD,1980_LTHS,1980_HS,1980_SomeColl,...,1990_GRAD,2000_LTHS,2000_HS,2000_SomeColl,2000_GRAD,2013_LTHS,2013_HS,2013_SomeColl,2013_GRAD,In Edu
2,01001,AL,Autauga County,54.8,31.1,7.7,6.4,40.6,35.2,12.1,...,14.5,21.3,33.8,26.9,18.0,12.3,33.6,29.1,25.0,1
3,01003,AL,Baldwin County,59.4,26.7,7.4,6.5,39.7,33.7,14.5,...,16.8,18.0,29.6,29.3,23.1,9.8,27.8,31.7,30.7,1
4,01005,AL,Barbour County,68.8,19.0,4.9,7.3,55.1,26.1,9.7,...,11.8,35.3,32.4,21.3,10.9,26.9,35.5,25.5,12.0,1
5,01007,AL,Bibb County,73.1,19.4,3.3,4.2,59.5,29.6,6.1,...,4.7,36.8,35.7,20.4,7.1,17.9,43.9,25.0,13.2,1
6,01009,AL,Blount County,70.5,22.7,4.1,2.7,53.9,32.4,8.4,...,7.0,29.6,36.0,24.8,9.6,20.2,32.3,34.4,13.1,1

In [12]:
xlsfile = os.path.join(raw_loc,'GDPByCounty2.csv')
gdp = pd.read_csv(xlsfile)
gdp.head()

,FIPS,Countyname,Postal,LineCode,IndustryName,2013,2014,2015
0,01001,Autauga,AL,1.0,All Industries,-4.4,-0.7,7.6
1,01001,Autauga,AL,2.0,Private goods-producing industries,4.4,3.9,4.7
2,01001,Autauga,AL,3.0,Private services-providing industries,-7.2,-2.2,9.9
3,01001,Autauga,AL,4.0,Government and government enterprises,-4.0,-1.5,0.3
4,01003,Baldwin,AL,1.0,All Industries,11.1,0.5,-4.3

In [13]:
# Keep only the all-industries line
gdp = gdp.loc[gdp["IndustryName"] == 'All Industries',:]

cols_in = gdp.columns
cols_rename = []
print('Original Column Names:')
print(cols_in)

for col in cols_in:
    
    if col == 'FIPS':
        cols_rename.append('FIPS')
    elif col == 'Countyname' :
        cols_rename.append("CountyNameGDP")
    elif col == '2013' :
        cols_rename.append("GDP_Change_2012_2013")
    elif col == '2014' :
        cols_rename.append("GDP_Change_2013_2014")
    elif col == '2015' :
        cols_rename.append("GDP_Change_2014_2015")
    else:
        cols_rename.append('DROP')
        
print('Renamed Column Names:')
print(cols_rename)

gdp.columns = cols_rename
gdp.drop(columns =['DROP'], inplace = True) 
gdp["In GDP"] = 1
gdp['CombinedCounty'] = 0

# Make sure the fips codes have leading zeros.
for row, rowvals in gdp.iterrows():
     
    if rowvals[1].find('+') > -1:
        gdp.loc[row,'CombinedCounty'] = 1

print('Final Column Names:')
print(gdp.columns)


gdp.head()

Original Column Names:
Index(['FIPS', 'Countyname', 'Postal', 'LineCode', 'IndustryName', '2013',
       '2014', '2015'],
      dtype='object')
Renamed Column Names:
['FIPS', 'CountyNameGDP', 'DROP', 'DROP', 'DROP', 'GDP_Change_2012_2013', 'GDP_Change_2013_2014', 'GDP_Change_2014_2015']
Final Column Names:
Index(['FIPS', 'CountyNameGDP', 'GDP_Change_2012_2013', 'GDP_Change_2013_2014',
       'GDP_Change_2014_2015', 'In GDP', 'CombinedCounty'],
      dtype='object')

,FIPS,CountyNameGDP,GDP_Change_2012_2013,GDP_Change_2013_2014,GDP_Change_2014_2015,In GDP,CombinedCounty
0,01001,Autauga,-4.4,-0.7,7.6,1,0
4,01003,Baldwin,11.1,0.5,-4.3,1,0
8,01005,Barbour,7.5,-3.5,6.8,1,0
12,01007,Bibb,5.7,-2.8,-4.5,1,0
16,01009,Blount,8.1,-3.3,17.7,1,0

In [14]:
# Output the combination counties so we can separate them, look up county codes and append them back on
combos = gdp.loc[gdp['CombinedCounty']==1,:]
countycheck_csv = os.path.join('..','RawData','combined_counties.csv')
countycheck_out = combos.to_csv(countycheck_csv,index=False)
combos.head()

,FIPS,CountyNameGDP,GDP_Change_2012_2013,GDP_Change_2013_2014,GDP_Change_2014_2015,In GDP,CombinedCounty
2196,15901,Maui + Kalawao,0.6,2.2,3.4,1,1
11604,51901,Albemarle + Charlottesville,-0.4,2.2,2.1,1,1
11608,51903,Alleghany + Covington,5.5,-5.0,6.5,1,1
11612,51907,"Augusta, Staunton + Waynesboro",2.3,0.5,4.0,1,1
11616,51911,Campbell + Lynchburg,-1.4,-0.2,-0.3,1,1

In [15]:
# pull in the spreadsheet with the combined counties separated out
combosfixed = pd.read_csv(os.path.join(raw_loc,'combined_counties_separated.csv'))
combosfixed['FIPS'] = combosfixed.FIPS.astype(object)
combosfixed.dtypes

FIPS                     object
CountyNameGDP            object
GDP_Change_2012_2013    float64
GDP_Change_2013_2014    float64
GDP_Change_2014_2015    float64
In GDP                    int64
CombinedCounty            int64
dtype: object

In [16]:
len_b4 = len(gdp)
gdp = gdp.loc[gdp['CombinedCounty']==0,:]
len_during = len(gdp)
gdp = pd.concat([gdp,combosfixed])
len_after = len(gdp)

print("Added separate entries for combined counties in GDP data")
print(f"Length before removing combinations: {len_b4}")
print(f"Length after removing combinations: {len_during}")
print(f"Length after adding fixed combinations: {len_after}")

gdp.head()

Added separate entries for combined counties in GDP data
Length before removing combinations: 3113
Length after removing combinations: 3089
Length after adding fixed combinations: 3142

,FIPS,CountyNameGDP,GDP_Change_2012_2013,GDP_Change_2013_2014,GDP_Change_2014_2015,In GDP,CombinedCounty
0,01001,Autauga,-4.4,-0.7,7.6,1,0
4,01003,Baldwin,11.1,0.5,-4.3,1,0
8,01005,Barbour,7.5,-3.5,6.8,1,0
12,01007,Bibb,5.7,-2.8,-4.5,1,0
16,01009,Blount,8.1,-3.3,17.7,1,0

In [17]:
check_gdp = gdp.loc[gdp["CombinedCounty"]==1,:]
check_gdp.head(50)

,FIPS,CountyNameGDP,GDP_Change_2012_2013,GDP_Change_2013_2014,GDP_Change_2014_2015,In GDP,CombinedCounty
0,15009,Maui,0.6,2.2,3.4,1,1
1,15005,Kalawao,0.6,2.2,3.4,1,1
2,51003,Albemarle,-0.4,2.2,2.1,1,1
3,51540,Charlottesville,-0.4,2.2,2.1,1,1
4,51005,Alleghany,5.5,-5,6.5,1,1
5,51580,Covington,5.5,-5,6.5,1,1
6,51015,Augusta,2.3,0.5,4,1,1
7,51790,Staunton,2.3,0.5,4,1,1
8,51820,Waynesboro,2.3,0.5,4,1,1
9,51031,Campbell,-1.4,-0.2,-0.3,1,1
10,51680,Lynchburg,-1.4,-0.2,-0.3,1,1
11,51035,Carroll,1,-0.4,1.6,1,1
12,51640,Galax,1,-0.4,1.6,1,1
13,51053,Dinwiddie,-0.5,-2.6,4,1,1
14,51570,Colonial Heights,-0.5,-2.6,4,1,1
15,51730,Petersburg,-0.5,-2.6,4,1,1
16,51059,Fairfax,0.1,0.6,1.4,1,1
17,51600,Fairfax City,0.1,0.6,1.4,1,1
18,51610,Falls Church,0.1,0.6,1.4,1,1
19,51069,Frederick,-3.1,-1.3,5,1,1
20,51840,Winchester,-3.1,-1.3,5,1,1
21,51081,Greensville,15,6.1,-2,1,1
22,51595,Emporia,15,6.1,-2,1,1
23,51089,Henry,-1,1.5,9,1,1
24,51690,Martinsville,-1,1.5,9,1,1
25,51095,James City,-2.8,-2.9,-1.3,1,1
26,51830,Williamsburg,-2.8,-2.9,-1.3,1,1
27,51121,Montgomery,5.8,4.8,6.1,1,1
28,51750,Radford,5.8,4.8,6.1,1,1
29,51143,Pittsylvania,-0.4,-2.8,-2.2,1,1
30,51590,Danville,-0.4,-2.8,-2.2,1,1
31,51149,Prince George,-1.7,-5.3,0.1,1,1
32,51670,Hopewell,-1.7,-5.3,0.1,1,1
33,51153,Prince William,1.2,2.3,0.5,1,1
34,51683,Manassas,1.2,2.3,0.5,1,1
35,51685,Manassas Park,1.2,2.3,0.5,1,1
36,51161,Roanoke County,2.8,0.9,2.3,1,1
37,51775,Salem,2.8,0.9,2.3,1,1
38,51163,Rockbridge,-6.9,-0.3,-0.8,1,1
39,51530,Buena Vista,-6.9,-0.3,-0.8,1,1
40,51678,Lexington,-6.9,-0.3,-0.8,1,1
41,51165,Rockingham,0.9,-3.8,-1.4,1,1
42,51660,Harrisonburg,0.9,-3.8,-1.4,1,1
43,51175,Southampton,-4.1,-1.2,2.9,1,1
44,51620,Franklin,-4.1,-1.2,2.9,1,1
45,51177,Spotsylvania,4.4,-0.4,6.1,1,1
46,51630,Fredericksburg,4.4,-0.4,6.1,1,1
47,51191,Washington,-6.9,-13.1,-2.4,1,1
48,51520,Bristol,-6.9,-13.1,-2.4,1,1
49,51195,Wise,-8.6,0.9,-3.5,1,1

In [18]:
all_county_info = pd.merge(pcpi,\
                  pd.merge(unemp,\
                  pd.merge(edu,gdp,on='FIPS',how='outer'),on='FIPS',how='outer'),on='FIPS',how='outer')

# Clean up county names where necessary
for obs,row in all_county_info.iterrows():

    if str(all_county_info.loc[obs,'FIPS']) == '02270':
        all_county_info.loc[obs,'County Name'] = 'Wade Hampton'
        all_county_info.loc[obs,'State Abbr'] = 'AK'
        
    if all_county_info.loc[obs,'CombinedCounty'] == 1:
        
        if str(all_county_info.loc[obs,'FIPS'])[0:2] == '15':
            all_county_info.loc[obs,'State Abbr'] = "HI"
        elif str(all_county_info.loc[obs,'FIPS'])[0:2] == '51':
            all_county_info.loc[obs,'State Abbr'] = "VA"
        all_county_info.loc[obs,'County Name'] = all_county_info.loc[obs,'CountyNameGDP'] 
        

all_county_info.head()

,FIPS,PCPI_2001,PCPI_2002,PCPI_2003,PCPI_2004,PCPI_2005,PCPI_2006,PCPI_2007,PCPI_2008,PCPI_2009,...,2013_HS,2013_SomeColl,2013_GRAD,In Edu,CountyNameGDP,GDP_Change_2012_2013,GDP_Change_2013_2014,GDP_Change_2014_2015,In GDP,CombinedCounty
0,45001,23201.0,21528.0,20359.0,21756.0,22375.0,23410.0,24311.0,25712.0,25702.0,...,34.3,29.5,14.7,1.0,Abbeville,-2.5,-4.7,-0.8,1.0,0.0
1,22001,21019.0,21565.0,22264.0,22569.0,24134.0,25908.0,27751.0,31483.0,31140.0,...,40.8,24.7,12.2,1.0,Acadia,-6.9,-0.5,-0.3,1.0,0.0
2,51001,21119.0,22156.0,23971.0,25337.0,26630.0,27828.0,29914.0,32114.0,32607.0,...,39.0,23.6,19.6,1.0,Accomack,2.2,-1.0,2.2,1.0,0.0
3,16001,33528.0,34195.0,34676.0,36657.0,37544.0,40471.0,40561.0,39479.0,37727.0,...,22.4,34.7,37.6,1.0,Ada,5.9,3.9,1.3,1.0,0.0
4,29001,21125.0,21065.0,21269.0,22361.0,23133.0,24114.0,25295.0,26552.0,27800.0,...,35.6,23.9,31.0,1.0,Adair,1.7,1.1,5.7,1.0,0.0

In [19]:
# Find places where the county and state name are blank.
data2check = all_county_info.loc[all_county_info["State Abbr"].isnull() == True,['FIPS','FIPS Out','In PCPI',\
                                                                                 'In Edu','In GDP','In Unemp','State Abbr',\
                                                                                 'County Name','CountyNameGDP',\
                                                                                 'GDP_Change_2012_2013', \
                                                                                 'GDP_Change_2013_2014',\
                                                                                 'GDP_Change_2014_2015', ]]
print(len(data2check))
data2check.head(30)

0

C:\Users\laslo\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

Empty DataFrame
Columns: [FIPS, FIPS Out, In PCPI, In Edu, In GDP, In Unemp, State Abbr, County Name, CountyNameGDP, GDP_Change_2012_2013, GDP_Change_2013_2014, GDP_Change_2014_2015]
Index: []

In [20]:
data2check2 = all_county_info.loc[all_county_info['In PCPI'] + all_county_info['In GDP'] + \
                                  all_county_info['In Edu'] + all_county_info['In Unemp'] != 4,\
                                  ['FIPS','In PCPI','In Edu','In Unemp','In GDP','State Abbr','County Name']]
print(f"There are {len(data2check2)} counties that are not in all four input datasets")
data2check2.head()

There are 200 counties that are not in all four input datasets

,FIPS,In PCPI,In Edu,In Unemp,In GDP,State Abbr,County Name
278,08014,1.0,1.0,NaN,1.0,CO,Broomfield County
1511,02270,1.0,NaN,1.0,NaN,AK,Wade Hampton
2204,02195,1.0,1.0,NaN,1.0,AK,Petersburg Census Area
2575,02230,1.0,1.0,NaN,1.0,AK,Skagway Municipality
3052,02275,1.0,1.0,NaN,1.0,AK,Wrangell City and Borough

In [21]:
county_csv = os.path.join('..','CleanData','CountyLevelData.csv')
county_out = all_county_info.to_csv(county_csv,index=False)

In [22]:
vnames = all_county_info.columns.tolist()

In [23]:
# Create a dictionary to hold state and county fips codes
# fipsdict has the state and county associated with each fips code
fipsdict = {}

# Go through the list of counties in our data and make sure each is 
# represented in the fipsdict. This will allow us to have FIPS, STATEFP,
# and COUNTYFP on each geojson file.
for row, rowvals in all_county_info.iterrows():
    
    # pull information from dataframe into temporary variables
    FIPS = str(rowvals[0])
    STATEFP = str(FIPS)[0:2]
    COUNTYFP = str(FIPS)[2:5]
    
    # If we have not yet seen this FIPS code, add it to the dictionary
    if FIPS not in fipsdict:
        fipsdict[FIPS]={}
 
    # Append the data for this county to its entry in the dictionary
    fipsdict[FIPS]={
        "STATEFP": STATEFP,
        "COUNTYFP": COUNTYFP}
    
fipsdict

{'45001': {'STATEFP': '45', 'COUNTYFP': '001'},
 '22001': {'STATEFP': '22', 'COUNTYFP': '001'},
 '51001': {'STATEFP': '51', 'COUNTYFP': '001'},
 '16001': {'STATEFP': '16', 'COUNTYFP': '001'},
 '29001': {'STATEFP': '29', 'COUNTYFP': '001'},
 '40001': {'STATEFP': '40', 'COUNTYFP': '001'},
 '19001': {'STATEFP': '19', 'COUNTYFP': '001'},
 '21001': {'STATEFP': '21', 'COUNTYFP': '001'},
 '53001': {'STATEFP': '53', 'COUNTYFP': '001'},
 '39001': {'STATEFP': '39', 'COUNTYFP': '001'},
 '42001': {'STATEFP': '42', 'COUNTYFP': '001'},
 '16003': {'STATEFP': '16', 'COUNTYFP': '003'},
 '28001': {'STATEFP': '28', 'COUNTYFP': '001'},
 '38001': {'STATEFP': '38', 'COUNTYFP': '001'},
 '19003': {'STATEFP': '19', 'COUNTYFP': '003'},
 '31001': {'STATEFP': '31', 'COUNTYFP': '001'},
 '18001': {'STATEFP': '18', 'COUNTYFP': '001'},
 '55001': {'STATEFP': '55', 'COUNTYFP': '001'},
 '17001': {'STATEFP': '17', 'COUNTYFP': '001'},
 '08001': {'STATEFP': '08', 'COUNTYFP': '001'},
 '50001': {'STATEFP': '50', 'COUNTYFP': '001'},
 '45003': {'STATEFP': '45', 'COUNTYFP': '003'},
 '27001': {'STATEFP': '27', 'COUNTYFP': '001'},
 '12001': {'STATEFP': '12', 'COUNTYFP': '001'},
 '37001': {'STATEFP': '37', 'COUNTYFP': '001'},
 '06001': {'STATEFP': '06', 'COUNTYFP': '001'},
 '08003': {'STATEFP': '08', 'COUNTYFP': '003'},
 '36001': {'STATEFP': '36', 'COUNTYFP': '001'},
 '56001': {'STATEFP': '56', 'COUNTYFP': '001'},
 '26001': {'STATEFP': '26', 'COUNTYFP': '001'},
 '28003': {'STATEFP': '28', 'COUNTYFP': '003'},
 '02013': {'STATEFP': '02', 'COUNTYFP': '013'},
 '02016': {'STATEFP': '02', 'COUNTYFP': '016'},
 '37003': {'STATEFP': '37', 'COUNTYFP': '003'},
 '17003': {'STATEFP': '17', 'COUNTYFP': '003'},
 '51510': {'STATEFP': '51', 'COUNTYFP': '510'},
 '40003': {'STATEFP': '40', 'COUNTYFP': '003'},
 '26003': {'STATEFP': '26', 'COUNTYFP': '003'},
 '19005': {'STATEFP': '19', 'COUNTYFP': '005'},
 '26005': {'STATEFP': '26', 'COUNTYFP': '005'},
 '24001': {'STATEFP': '24', 'COUNTYFP': '001'},
 '36003': {'STATEFP': '36', 'COUNTYFP': '003'},
 '37005': {'STATEFP': '37', 'COUNTYFP': '005'},
 '42003': {'STATEFP': '42', 'COUNTYFP': '003'},
 '39003': {'STATEFP': '39', 'COUNTYFP': '003'},
 '20001': {'STATEFP': '20', 'COUNTYFP': '001'},
 '22003': {'STATEFP': '22', 'COUNTYFP': '003'},
 '18003': {'STATEFP': '18', 'COUNTYFP': '003'},
 '21003': {'STATEFP': '21', 'COUNTYFP': '003'},
 '45005': {'STATEFP': '45', 'COUNTYFP': '005'},
 '26007': {'STATEFP': '26', 'COUNTYFP': '007'},
 '06003': {'STATEFP': '06', 'COUNTYFP': '003'},
 '06005': {'STATEFP': '06', 'COUNTYFP': '005'},
 '51007': {'STATEFP': '51', 'COUNTYFP': '007'},
 '51009': {'STATEFP': '51', 'COUNTYFP': '009'},
 '28005': {'STATEFP': '28', 'COUNTYFP': '005'},
 '02020': {'STATEFP': '02', 'COUNTYFP': '020'},
 '45007': {'STATEFP': '45', 'COUNTYFP': '007'},
 '21005': {'STATEFP': '21', 'COUNTYFP': '005'},
 '47001': {'STATEFP': '47', 'COUNTYFP': '001'},
 '48001': {'STATEFP': '48', 'COUNTYFP': '001'},
 '20003': {'STATEFP': '20', 'COUNTYFP': '003'},
 '29003': {'STATEFP': '29', 'COUNTYFP': '003'},
 '48003': {'STATEFP': '48', 'COUNTYFP': '003'},
 '23001': {'STATEFP': '23', 'COUNTYFP': '001'},
 '48005': {'STATEFP': '48', 'COUNTYFP': '005'},
 '24003': {'STATEFP': '24', 'COUNTYFP': '003'},
 '27003': {'STATEFP': '27', 'COUNTYFP': '003'},
 '37007': {'STATEFP': '37', 'COUNTYFP': '007'},
 '31003': {'STATEFP': '31', 'COUNTYFP': '003'},
 '26009': {'STATEFP': '26', 'COUNTYFP': '009'},
 '04001': {'STATEFP': '04', 'COUNTYFP': '001'},
 '19007': {'STATEFP': '19', 'COUNTYFP': '007'},
 '13001': {'STATEFP': '13', 'COUNTYFP': '001'},
 '51011': {'STATEFP': '51', 'COUNTYFP': '011'},
 '48007': {'STATEFP': '48', 'COUNTYFP': '007'},
 '08005': {'STATEFP': '08', 'COUNTYFP': '005'},
 '48009': {'STATEFP': '48', 'COUNTYFP': '009'},
 '08007': {'STATEFP': '08', 'COUNTYFP': '007'},
 '26011': {'STATEFP': '26', 'COUNTYFP': '011'},
 '05001': {'STATEFP': '05', 'COUNTYFP': '001'},
 '51013': {'STATEFP': '51', 'COUNTYFP': '013'},
 '48011': {'STATEFP': '48', 'COUNTYFP': '011'},
 '42005': {'STATEFP': '42', 'COUNTYFP': '005'},
 '23003': {'STATEFP': '23', 'COUNTYFP': '003'},
 '31005': {'STATEFP': '31', 'COUNTYFP': '005'},
 '22005': {'STATEFP': '22', 'COUNTYFP': '005'},
 '37009': {'STATEFP': '37', 'COUNTYFP': '009'},
 '39005': {'STATEFP': '39', 'COUNTYFP': '005'},
 '55003': {'STATEFP': '55', 'COUNTYFP': '003'},
 '05003': {'STATEFP': '05', 'COUNTYFP': '003'},
 '39007': {'STATEFP': '39', 'COUNTYFP': '007'},
 '53003': {'STATEFP': '53', 'COUNTYFP': '003'},
 '22007': {'STATEFP': '22', 'COUNTYFP': '007'},
 '48013': {'STATEFP': '48', 'COUNTYFP': '013'},
 '29005': {'STATEFP': '29', 'COUNTYFP': '005'},
 '20005': {'STATEFP': '20', 'COUNTYFP': '005'},
 '39009': {'STATEFP': '39', 'COUNTYFP': '009'},
 '13003': {'STATEFP': '13', 'COUNTYFP': '003'},
 '34001': {'STATEFP': '34', 'COUNTYFP': '001'},
 '40005': {'STATEFP': '40', 'COUNTYFP': '005'},
 '28007': {'STATEFP': '28', 'COUNTYFP': '007'},
 '29007': {'STATEFP': '29', 'COUNTYFP': '007'},
 '19009': {'STATEFP': '19', 'COUNTYFP': '009'},
 '39011': {'STATEFP': '39', 'COUNTYFP': '011'},
 '46003': {'STATEFP': '46', 'COUNTYFP': '003'},
 '48015': {'STATEFP': '48', 'COUNTYFP': '015'},
 '01001': {'STATEFP': '01', 'COUNTYFP': '001'},
 '37011': {'STATEFP': '37', 'COUNTYFP': '011'},
 '22009': {'STATEFP': '22', 'COUNTYFP': '009'},
 '08009': {'STATEFP': '08', 'COUNTYFP': '009'},
 '13005': {'STATEFP': '13', 'COUNTYFP': '005'},
 '48017': {'STATEFP': '48', 'COUNTYFP': '017'},
 '41001': {'STATEFP': '41', 'COUNTYFP': '001'},
 '12003': {'STATEFP': '12', 'COUNTYFP': '003'},
 '13007': {'STATEFP': '13', 'COUNTYFP': '007'},
 '13009': {'STATEFP': '13', 'COUNTYFP': '009'},
 '01003': {'STATEFP': '01', 'COUNTYFP': '003'},
 '21007': {'STATEFP': '21', 'COUNTYFP': '007'},
 '24005': {'STATEFP': '24', 'COUNTYFP': '005'},
 '24510': {'STATEFP': '24', 'COUNTYFP': '510'},
 '45009': {'STATEFP': '45', 'COUNTYFP': '009'},
 '48019': {'STATEFP': '48', 'COUNTYFP': '019'},
 '13011': {'STATEFP': '13', 'COUNTYFP': '011'},
 '31007': {'STATEFP': '31', 'COUNTYFP': '007'},
 '16005': {'STATEFP': '16', 'COUNTYFP': '005'},
 '26013': {'STATEFP': '26', 'COUNTYFP': '013'},
 '20007': {'STATEFP': '20', 'COUNTYFP': '007'},
 '54001': {'STATEFP': '54', 'COUNTYFP': '001'},
 '01005': {'STATEFP': '01', 'COUNTYFP': '005'},
 '38003': {'STATEFP': '38', 'COUNTYFP': '003'},
 '25001': {'STATEFP': '25', 'COUNTYFP': '001'},
 '45011': {'STATEFP': '45', 'COUNTYFP': '011'},
 '21009': {'STATEFP': '21', 'COUNTYFP': '009'},
 '55005': {'STATEFP': '55', 'COUNTYFP': '005'},
 '13013': {'STATEFP': '13', 'COUNTYFP': '013'},
 '26015': {'STATEFP': '26', 'COUNTYFP': '015'},
 '29009': {'STATEFP': '29', 'COUNTYFP': '009'},
 '18005': {'STATEFP': '18', 'COUNTYFP': '005'},
 '20009': {'STATEFP': '20', 'COUNTYFP': '009'},
 '29011': {'STATEFP': '29', 'COUNTYFP': '011'},
 '13015': {'STATEFP': '13', 'COUNTYFP': '015'},
 '48021': {'STATEFP': '48', 'COUNTYFP': '021'},
 '29013': {'STATEFP': '29', 'COUNTYFP': '013'},
 '21011': {'STATEFP': '21', 'COUNTYFP': '011'},
 '51017': {'STATEFP': '51', 'COUNTYFP': '017'},
 '05005': {'STATEFP': '05', 'COUNTYFP': '005'},
 '12005': {'STATEFP': '12', 'COUNTYFP': '005'},
 '26017': {'STATEFP': '26', 'COUNTYFP': '017'},
 '55007': {'STATEFP': '55', 'COUNTYFP': '007'},
 '48023': {'STATEFP': '48', 'COUNTYFP': '023'},
 '46005': {'STATEFP': '46', 'COUNTYFP': '005'},
 '16007': {'STATEFP': '16', 'COUNTYFP': '007'},
 '37013': {'STATEFP': '37', 'COUNTYFP': '013'},
 '45013': {'STATEFP': '45', 'COUNTYFP': '013'},
 '22011': {'STATEFP': '22', 'COUNTYFP': '011'},
 '49001': {'STATEFP': '49', 'COUNTYFP': '001'},
 '40007': {'STATEFP': '40', 'COUNTYFP': '007'},
 '42007': {'STATEFP': '42', 'COUNTYFP': '007'},
 '30001': {'STATEFP': '30', 'COUNTYFP': '001'},
 '27005': {'STATEFP': '27', 'COUNTYFP': '005'},
 '40009': {'STATEFP': '40', 'COUNTYFP': '009'},
 '51019': {'STATEFP': '51', 'COUNTYFP': '019'},
 '47003': {'STATEFP': '47', 'COUNTYFP': '003'},
 '42009': {'STATEFP': '42', 'COUNTYFP': '009'},
 '48025': {'STATEFP': '48', 'COUNTYFP': '025'},
 '33001': {'STATEFP': '33', 'COUNTYFP': '001'},
 '21013': {'STATEFP': '21', 'COUNTYFP': '013'},
 '48027': {'STATEFP': '48', 'COUNTYFP': '027'},
 '39013': {'STATEFP': '39', 'COUNTYFP': '013'},
 '27007': {'STATEFP': '27', 'COUNTYFP': '007'},
 '13017': {'STATEFP': '13', 'COUNTYFP': '017'},
 '16009': {'STATEFP': '16', 'COUNTYFP': '009'},
 '46007': {'STATEFP': '46', 'COUNTYFP': '007'},
 '50003': {'STATEFP': '50', 'COUNTYFP': '003'},
 '38005': {'STATEFP': '38', 'COUNTYFP': '005'},
 '08011': {'STATEFP': '08', 'COUNTYFP': '011'},
 '47005': {'STATEFP': '47', 'COUNTYFP': '005'},
 '41003': {'STATEFP': '41', 'COUNTYFP': '003'},
 '19011': {'STATEFP': '19', 'COUNTYFP': '011'},
 '53005': {'STATEFP': '53', 'COUNTYFP': '005'},
 '27009': {'STATEFP': '27', 'COUNTYFP': '009'},
 '05007': {'STATEFP': '05', 'COUNTYFP': '007'},
 '18007': {'STATEFP': '18', 'COUNTYFP': '007'},
 '28009': {'STATEFP': '28', 'COUNTYFP': '009'},
 '29015': {'STATEFP': '29', 'COUNTYFP': '015'},
 '26019': {'STATEFP': '26', 'COUNTYFP': '019'},
 '34003': {'STATEFP': '34', 'COUNTYFP': '003'},
 '45015': {'STATEFP': '45', 'COUNTYFP': '015'},
 '54003': {'STATEFP': '54', 'COUNTYFP': '003'},
 '42011': {'STATEFP': '42', 'COUNTYFP': '011'},
 '25003': {'STATEFP': '25', 'COUNTYFP': '003'},
 '35001': {'STATEFP': '35', 'COUNTYFP': '001'},
 '26021': {'STATEFP': '26', 'COUNTYFP': '021'},
 '13019': {'STATEFP': '13', 'COUNTYFP': '019'},
 '37015': {'STATEFP': '37', 'COUNTYFP': '015'},
 '02050': {'STATEFP': '02', 'COUNTYFP': '050'},
 '48029': {'STATEFP': '48', 'COUNTYFP': '029'},
 '13021': {'STATEFP': '13', 'COUNTYFP': '021'},
 '01007': {'STATEFP': '01', 'COUNTYFP': '007'},
 '22013': {'STATEFP': '22', 'COUNTYFP': '013'},
 '30003': {'STATEFP': '30', 'COUNTYFP': '003'},
 '56003': {'STATEFP': '56', 'COUNTYFP': '003'},
 '27011': {'STATEFP': '27', 'COUNTYFP': '011'},
 '38007': {'STATEFP': '38', 'COUNTYFP': '007'},
 '16011': {'STATEFP': '16', 'COUNTYFP': '011'},
 '19013': {'STATEFP': '19', 'COUNTYFP': '013'},
 '18009': {'STATEFP': '18', 'COUNTYFP': '009'},
 '37017': {'STATEFP': '37', 'COUNTYFP': '017'},
 '16013': {'STATEFP': '16', 'COUNTYFP': '013'},
 '30005': {'STATEFP': '30', 'COUNTYFP': '005'},
 '31009': {'STATEFP': '31', 'COUNTYFP': '009'},
 '40011': {'STATEFP': '40', 'COUNTYFP': '011'},
 '42013': {'STATEFP': '42', 'COUNTYFP': '013'},
 '48031': {'STATEFP': '48', 'COUNTYFP': '031'},
 '51021': {'STATEFP': '51', 'COUNTYFP': '021'},
 '13023': {'STATEFP': '13', 'COUNTYFP': '023'},
 '47007': {'STATEFP': '47', 'COUNTYFP': '007'},
 '01009': {'STATEFP': '01', 'COUNTYFP': '009'},
 '47009': {'STATEFP': '47', 'COUNTYFP': '009'},
 '27013': {'STATEFP': '27', 'COUNTYFP': '013'},
 '16015': {'STATEFP': '16', 'COUNTYFP': '015'},
 '28011': {'STATEFP': '28', 'COUNTYFP': '011'},
 '29017': {'STATEFP': '29', 'COUNTYFP': '017'},
 '46009': {'STATEFP': '46', 'COUNTYFP': '009'},
 '17005': {'STATEFP': '17', 'COUNTYFP': '005'},
 '16017': {'STATEFP': '16', 'COUNTYFP': '017'},
 '16019': {'STATEFP': '16', 'COUNTYFP': '019'},
 '29019': {'STATEFP': '29', 'COUNTYFP': '019'},
 '19015': {'STATEFP': '19', 'COUNTYFP': '015'},
 '21015': {'STATEFP': '21', 'COUNTYFP': '015'},
 '18011': {'STATEFP': '18', 'COUNTYFP': '011'},
 '54005': {'STATEFP': '54', 'COUNTYFP': '005'},
 '31011': {'STATEFP': '31', 'COUNTYFP': '011'},
 '17007': {'STATEFP': '17', 'COUNTYFP': '007'},
 '05009': {'STATEFP': '05', 'COUNTYFP': '009'},
 '48033': {'STATEFP': '48', 'COUNTYFP': '033'},
 '48035': {'STATEFP': '48', 'COUNTYFP': '035'},
 '22015': {'STATEFP': '22', 'COUNTYFP': '015'},
 '51023': {'STATEFP': '51', 'COUNTYFP': '023'},
 '38009': {'STATEFP': '38', 'COUNTYFP': '009'},
 '08013': {'STATEFP': '08', 'COUNTYFP': '013'},
 '16021': {'STATEFP': '16', 'COUNTYFP': '021'},
 '21017': {'STATEFP': '21', 'COUNTYFP': '017'},
 '20011': {'STATEFP': '20', 'COUNTYFP': '011'},
 '48037': {'STATEFP': '48', 'COUNTYFP': '037'},
 '38011': {'STATEFP': '38', 'COUNTYFP': '011'},
 '31013': {'STATEFP': '31', 'COUNTYFP': '013'},
 '49003': {'STATEFP': '49', 'COUNTYFP': '003'},
 '21019': {'STATEFP': '21', 'COUNTYFP': '019'},
 '31015': {'STATEFP': '31', 'COUNTYFP': '015'},
 '21021': {'STATEFP': '21', 'COUNTYFP': '021'},
 '21023': {'STATEFP': '21', 'COUNTYFP': '023'},
 '42015': {'STATEFP': '42', 'COUNTYFP': '015'},
 '12007': {'STATEFP': '12', 'COUNTYFP': '007'},
 '47011': {'STATEFP': '47', 'COUNTYFP': '011'},
 '05011': {'STATEFP': '05', 'COUNTYFP': '011'},
 '26023': {'STATEFP': '26', 'COUNTYFP': '023'},
 '13025': {'STATEFP': '13', 'COUNTYFP': '025'},
 '54007': {'STATEFP': '54', 'COUNTYFP': '007'},
 '48039': {'STATEFP': '48', 'COUNTYFP': '039'},
 '48041': {'STATEFP': '48', 'COUNTYFP': '041'},
 '21025': {'STATEFP': '21', 'COUNTYFP': '025'},
 '21027': {'STATEFP': '21', 'COUNTYFP': '027'},
 '19017': {'STATEFP': '19', 'COUNTYFP': '017'},
 '12009': {'STATEFP': '12', 'COUNTYFP': '009'},
 '48043': {'STATEFP': '48', 'COUNTYFP': '043'},
 '48045': {'STATEFP': '48', 'COUNTYFP': '045'},
 '44001': {'STATEFP': '44', 'COUNTYFP': '001'},
 '25005': {'STATEFP': '25', 'COUNTYFP': '005'},
 '02060': {'STATEFP': '02', 'COUNTYFP': '060'},
 '30007': {'STATEFP': '30', 'COUNTYFP': '007'},
 '36005': {'STATEFP': '36', 'COUNTYFP': '005'},
 '54009': {'STATEFP': '54', 'COUNTYFP': '009'},
 '46011': {'STATEFP': '46', 'COUNTYFP': '011'},
 '48047': {'STATEFP': '48', 'COUNTYFP': '047'},
 '13027': {'STATEFP': '13', 'COUNTYFP': '027'},
 '36007': {'STATEFP': '36', 'COUNTYFP': '007'},
 '08014': {'STATEFP': '08', 'COUNTYFP': '014'},
 '12011': {'STATEFP': '12', 'COUNTYFP': '011'},
 '31017': {'STATEFP': '31', 'COUNTYFP': '017'},
 '46013': {'STATEFP': '46', 'COUNTYFP': '013'},
 '39015': {'STATEFP': '39', 'COUNTYFP': '015'},
 '55009': {'STATEFP': '55', 'COUNTYFP': '009'},
 '27015': {'STATEFP': '27', 'COUNTYFP': '015'},
 '20013': {'STATEFP': '20', 'COUNTYFP': '013'},
 '18013': {'STATEFP': '18', 'COUNTYFP': '013'},
 '48049': {'STATEFP': '48', 'COUNTYFP': '049'},
 '17009': {'STATEFP': '17', 'COUNTYFP': '009'},
 '46015': {'STATEFP': '46', 'COUNTYFP': '015'},
 '37019': {'STATEFP': '37', 'COUNTYFP': '019'},
 '51025': {'STATEFP': '51', 'COUNTYFP': '025'},
 '13029': {'STATEFP': '13', 'COUNTYFP': '029'},
 '40013': {'STATEFP': '40', 'COUNTYFP': '013'},
 '29021': {'STATEFP': '29', 'COUNTYFP': '021'},
 '51027': {'STATEFP': '51', 'COUNTYFP': '027'},
 '19019': {'STATEFP': '19', 'COUNTYFP': '019'},
 '51029': {'STATEFP': '51', 'COUNTYFP': '029'},
 '42017': {'STATEFP': '42', 'COUNTYFP': '017'},
 '19021': {'STATEFP': '19', 'COUNTYFP': '021'},
 '55011': {'STATEFP': '55', 'COUNTYFP': '011'},
 '46017': {'STATEFP': '46', 'COUNTYFP': '017'},
 '31019': {'STATEFP': '31', 'COUNTYFP': '019'},
 '21029': {'STATEFP': '21', 'COUNTYFP': '029'},
 '13031': {'STATEFP': '13', 'COUNTYFP': '031'},
 '01011': {'STATEFP': '01', 'COUNTYFP': '011'},
 '37021': {'STATEFP': '37', 'COUNTYFP': '021'},
 '17011': {'STATEFP': '17', 'COUNTYFP': '011'},
 '37023': {'STATEFP': '37', 'COUNTYFP': '023'},
 '13033': {'STATEFP': '13', 'COUNTYFP': '033'},
 '38013': {'STATEFP': '38', 'COUNTYFP': '013'},
 '38015': {'STATEFP': '38', 'COUNTYFP': '015'},
 '48051': {'STATEFP': '48', 'COUNTYFP': '051'},
 '34005': {'STATEFP': '34', 'COUNTYFP': '005'},
 '48053': {'STATEFP': '48', 'COUNTYFP': '053'},
 '55013': {'STATEFP': '55', 'COUNTYFP': '013'},
 '31021': {'STATEFP': '31', 'COUNTYFP': '021'},
 '31023': {'STATEFP': '31', 'COUNTYFP': '023'},
 '29023': {'STATEFP': '29', 'COUNTYFP': '023'},
 '01013': {'STATEFP': '01', 'COUNTYFP': '013'},
 '39017': {'STATEFP': '39', 'COUNTYFP': '017'},
 '19023': {'STATEFP': '19', 'COUNTYFP': '023'},
 '20015': {'STATEFP': '20', 'COUNTYFP': '015'},
 '21031': {'STATEFP': '21', 'COUNTYFP': '031'},
 '42019': {'STATEFP': '42', 'COUNTYFP': '019'},
 '16023': {'STATEFP': '16', 'COUNTYFP': '023'},
 '46019': {'STATEFP': '46', 'COUNTYFP': '019'},
 '06007': {'STATEFP': '06', 'COUNTYFP': '007'},
 '13035': {'STATEFP': '13', 'COUNTYFP': '035'},
 '37025': {'STATEFP': '37', 'COUNTYFP': '025'},
 '54011': {'STATEFP': '54', 'COUNTYFP': '011'},
 '49005': {'STATEFP': '49', 'COUNTYFP': '005'},
 '40015': {'STATEFP': '40', 'COUNTYFP': '015'},
 '22017': {'STATEFP': '22', 'COUNTYFP': '017'},
 '06009': {'STATEFP': '06', 'COUNTYFP': '009'},
 '22019': {'STATEFP': '22', 'COUNTYFP': '019'},
 '37027': {'STATEFP': '37', 'COUNTYFP': '027'},
 '22021': {'STATEFP': '22', 'COUNTYFP': '021'},
 '21033': {'STATEFP': '21', 'COUNTYFP': '033'},
 '29025': {'STATEFP': '29', 'COUNTYFP': '025'},
 '48055': {'STATEFP': '48', 'COUNTYFP': '055'},
 '50005': {'STATEFP': '50', 'COUNTYFP': '005'},
 '54013': {'STATEFP': '54', 'COUNTYFP': '013'},
 '17013': {'STATEFP': '17', 'COUNTYFP': '013'},
 '48057': {'STATEFP': '48', 'COUNTYFP': '057'},
 '19025': {'STATEFP': '19', 'COUNTYFP': '025'},
 '26025': {'STATEFP': '26', 'COUNTYFP': '025'},
 '45017': {'STATEFP': '45', 'COUNTYFP': '017'},
 '01015': {'STATEFP': '01', 'COUNTYFP': '015'},
 '28013': {'STATEFP': '28', 'COUNTYFP': '013'},
 '13037': {'STATEFP': '13', 'COUNTYFP': '037'},
 '05013': {'STATEFP': '05', 'COUNTYFP': '013'},
 '12013': {'STATEFP': '12', 'COUNTYFP': '013'},
 '48059': {'STATEFP': '48', 'COUNTYFP': '059'},
 '29027': {'STATEFP': '29', 'COUNTYFP': '027'},
 '21035': {'STATEFP': '21', 'COUNTYFP': '035'},
 '55015': {'STATEFP': '55', 'COUNTYFP': '015'},
 '24009': {'STATEFP': '24', 'COUNTYFP': '009'},
 '16025': {'STATEFP': '16', 'COUNTYFP': '025'},
 '42021': {'STATEFP': '42', 'COUNTYFP': '021'},
 '34007': {'STATEFP': '34', 'COUNTYFP': '007'},
 '29029': {'STATEFP': '29', 'COUNTYFP': '029'},
 '13039': {'STATEFP': '13', 'COUNTYFP': '039'},
 '37029': {'STATEFP': '37', 'COUNTYFP': '029'},
 '48061': {'STATEFP': '48', 'COUNTYFP': '061'},
 '22023': {'STATEFP': '22', 'COUNTYFP': '023'},
 '42023': {'STATEFP': '42', 'COUNTYFP': '023'},
 '48063': {'STATEFP': '48', 'COUNTYFP': '063'},
 '56005': {'STATEFP': '56', 'COUNTYFP': '005'},
 '47013': {'STATEFP': '47', 'COUNTYFP': '013'},
 '21037': {'STATEFP': '21', 'COUNTYFP': '037'},
 '46021': {'STATEFP': '46', 'COUNTYFP': '021'},
 '40017': {'STATEFP': '40', 'COUNTYFP': '017'},
 '13043': {'STATEFP': '13', 'COUNTYFP': '043'},
 '47015': {'STATEFP': '47', 'COUNTYFP': '015'},
 '16027': {'STATEFP': '16', 'COUNTYFP': '027'},
 '29031': {'STATEFP': '29', 'COUNTYFP': '031'},
 '34009': {'STATEFP': '34', 'COUNTYFP': '009'},
 '42025': {'STATEFP': '42', 'COUNTYFP': '025'},
 '49007': {'STATEFP': '49', 'COUNTYFP': '007'},
 '30009': {'STATEFP': '30', 'COUNTYFP': '009'},
 '56007': {'STATEFP': '56', 'COUNTYFP': '007'},
 '16029': {'STATEFP': '16', 'COUNTYFP': '029'},
 '21039': {'STATEFP': '21', 'COUNTYFP': '039'},
 '27017': {'STATEFP': '27', 'COUNTYFP': '017'},
 '24011': {'STATEFP': '24', 'COUNTYFP': '011'},
 '51033': {'STATEFP': '51', 'COUNTYFP': '033'},
 '17015': {'STATEFP': '17', 'COUNTYFP': '015'},
 '33003': {'STATEFP': '33', 'COUNTYFP': '003'},
 '18015': {'STATEFP': '18', 'COUNTYFP': '015'},
 '13045': {'STATEFP': '13', 'COUNTYFP': '045'},
 '28015': {'STATEFP': '28', 'COUNTYFP': '015'},
 '39019': {'STATEFP': '39', 'COUNTYFP': '019'},
 '21041': {'STATEFP': '21', 'COUNTYFP': '041'},
 '29033': {'STATEFP': '29', 'COUNTYFP': '033'},
 '19027': {'STATEFP': '19', 'COUNTYFP': '027'},
 '24013': {'STATEFP': '24', 'COUNTYFP': '013'},
 '05015': {'STATEFP': '05', 'COUNTYFP': '015'},
 '47017': {'STATEFP': '47', 'COUNTYFP': '017'},
 '48065': {'STATEFP': '48', 'COUNTYFP': '065'},
 '32510': {'STATEFP': '32', 'COUNTYFP': '510'},
 '47019': {'STATEFP': '47', 'COUNTYFP': '019'},
 '21043': {'STATEFP': '21', 'COUNTYFP': '043'},
 '30011': {'STATEFP': '30', 'COUNTYFP': '011'},
 '29035': {'STATEFP': '29', 'COUNTYFP': '035'},
 '40019': {'STATEFP': '40', 'COUNTYFP': '019'},
 '37031': {'STATEFP': '37', 'COUNTYFP': '031'},
 '27019': {'STATEFP': '27', 'COUNTYFP': '019'},
 '30013': {'STATEFP': '30', 'COUNTYFP': '013'},
 '21045': {'STATEFP': '21', 'COUNTYFP': '045'},
 '31025': {'STATEFP': '31', 'COUNTYFP': '025'},
 '18017': {'STATEFP': '18', 'COUNTYFP': '017'},
 '19029': {'STATEFP': '19', 'COUNTYFP': '029'},
 '38017': {'STATEFP': '38', 'COUNTYFP': '017'},
 '17017': {'STATEFP': '17', 'COUNTYFP': '017'},
 '27021': {'STATEFP': '27', 'COUNTYFP': '021'},

In [24]:
# Create the initial geojson file by pulling records from the big/historical geojson
# and keeping only records that apply to that year.
def create_yearly_geojson(year):
    
    # create a reference to the output file
    outfile = os.path.join(clean_loc,f'FinalGeoFile{year}.json')

    # Create a numeric variable of the year to check against
    year2check = year
    
    # Create a blank list of the features we will keep
    features = []
    
    # Open up the existing geojson file and read it into the empty geojson dictionary created above.
    # While reading it in, pull the matching state and county fips from the data2add dictionary so we can add the unemployment info to the geojson.
    with open(big_geojson, 'r') as f:
        temp = json.load(f)
        
        for feature in temp['features']:
            
            featureProperties = feature['properties']
            FIPS = featureProperties['FIPS']
            
            start_year = int(featureProperties["START_DATE"][0:4])
            end_year = int(featureProperties["END_DATE"][0:4])
            
            # Add the state and county fips codes so this json will look
            # like the ones for later years from Census
            featureData = fipsdict.get(FIPS, {})
            for key in featureData.keys():
                featureProperties[key] = featureData[key]
        
            if start_year <= year2check and year2check <= end_year:
                features.append(feature)
                
    last_feature = len(features)-1
                
    # Output a new geojson file specific to this year.
    with open(outfile,'w') as f:
        f.write('{"type":"FeatureCollection","features": [')
        for feature in features:
            json.dump(feature, f)
            if features.index(feature) < last_feature:
                f.write(',')
        f.write(']}')

create_yearly_geojson(1970)
create_yearly_geojson(1980)
for year in range(1990,2000):
    create_yearly_geojson(year)        
create_yearly_geojson(2000)

In [25]:

def create_final_geojson(year):
    
    year2check = year
    
    # for years greater than 2000 we also need the two digit year
    yr = str(year2check)[2:4]
    
    # create a reference to the input geojson file. Different years have different files/formats
    if year2check <= 2000:
        infile = os.path.join(clean_loc,f'FinalGeoFile{year}.json')
    elif year2check <= 2007:
        infile = os.path.join(clean_loc,f'FinalGeoFile2000.json')
    elif year2check <= 2009:
        infile = os.path.join(raw_loc,f'tl_{year}_us_county00.json')
    elif year2check == 2010:
        infile = os.path.join(raw_loc,f'tl_2010_us_county10.json')
    elif year2check <= 2012:
        infile = os.path.join(raw_loc,f'tl_2010_us_county.json')
    else:
        infile = os.path.join(raw_loc,f'cb_{year}_us_county_20m.json')
    
    # create a reference to the output file
    outfile = os.path.join(clean_loc,f'FinalGeoFile{year}.json')
    
    # Create a blank dictionary to hold the data we will be tacking onto the geojson file
    data2add = {}

    # Loop through the dataframe and add information to the data2add dictionary. 
    # We will use this to put these values into the geojson.
    for row, rowvals in all_county_info.iterrows():
        
        # pull information from dataframe into temporary variables
        FIPS = rowvals[0]   
        STATEFP = str(rowvals[0])[0:2]
        COUNTYFP = str(rowvals[0])[2:5]
        StateAbbr = rowvals[vnames.index('State Abbr')]  
        CountyName = rowvals[vnames.index('County Name')]
        
        # pull monthly unemployment for this year, if it exists for this year
        if f'Unemp_{year}01' in vnames:
            temp01 = rowvals[vnames.index(f'Unemp_{year}01')]
            temp02 = rowvals[vnames.index(f'Unemp_{year}02')]
            temp03 = rowvals[vnames.index(f'Unemp_{year}03')]
            temp04 = rowvals[vnames.index(f'Unemp_{year}04')]
            temp05 = rowvals[vnames.index(f'Unemp_{year}05')]
            temp06 = rowvals[vnames.index(f'Unemp_{year}06')]
            temp07 = rowvals[vnames.index(f'Unemp_{year}07')]
            temp08 = rowvals[vnames.index(f'Unemp_{year}08')]
            temp09 = rowvals[vnames.index(f'Unemp_{year}09')]
            temp10 = rowvals[vnames.index(f'Unemp_{year}10')]
            temp11 = rowvals[vnames.index(f'Unemp_{year}11')]
            temp12 = rowvals[vnames.index(f'Unemp_{year}12')]
        else:
            temp01 = -1
            temp02 = -1
            temp03 = -1
            temp04 = -1
            temp05 = -1
            temp06 = -1
            temp07 = -1
            temp08 = -1
            temp09 = -1
            temp10 = -1
            temp11 = -1
            temp12 = -1

        # Pull per-capital personal income, if it exists for this year
        if f'PCPI_{year}' in vnames:
            PCPI = rowvals[vnames.index(f'PCPI_{year}')]
        else:
            PCPI = -1
            
        # Pull gdp, if it exists for this year
        if year2check == 2013:
            GDP = rowvals[vnames.index('GDP_Change_2012_2013')]
        elif year2check == 2014:
            GDP = rowvals[vnames.index('GDP_Change_2013_2014')]
        elif year2check == 2015:
            GDP = rowvals[vnames.index('GDP_Change_2014_2015')]
        else:
            GDP = -1

        # Pull eductional attainment, if it exists for this year
        if year2check in (1970, 1980, 1990, 2000, 2013):
            LTHS = rowvals[vnames.index(f'{year}_LTHS')]
            HS = rowvals[vnames.index(f'{year}_HS')]
            SomeColl = rowvals[vnames.index(f'{year}_SomeColl')]
            GRAD = rowvals[vnames.index(f'{year}_GRAD')]
        else:
            LTHS = -1
            HS = -1
            SomeColl = -1
            GRAD = -1
            
        # Check to see if this state/county has already been added to the dictionary.
        # If not, then add an entry for it.
        if FIPS not in data2add:
            data2add[FIPS]={}
        
        # Append the data for this county to its entry in the dictionary
        data2add[FIPS]={
            "StateAbbr": StateAbbr,
            "CountyName": CountyName,
            f"Unemp_{year}01" : temp01,
            f"Unemp_{year}02" : temp02,
            f"Unemp_{year}03" : temp03,
            f"Unemp_{year}04" : temp04,
            f"Unemp_{year}05" : temp05,
            f"Unemp_{year}06" : temp06,
            f"Unemp_{year}07" : temp07,
            f"Unemp_{year}08" : temp08,
            f"Unemp_{year}09" : temp09,
            f"Unemp_{year}10" : temp10,
            f"Unemp_{year}11" : temp11,
            f"Unemp_{year}12" : temp12,
            f"PCPI_{year}": PCPI,
            f"GDP_change_{year}": GDP,
            "LTHS" : LTHS,
            "HS" : HS,
            "SomeColl" : SomeColl,
            "GRAD" : GRAD
        }
    
    #print(data2add)
            
    # Create a blank geojson for the final result
    geojson = {}
    
    # Open up the existing geojson file and read it into the empty geojson dictionary created above.
    # While reading it in, pull the matching state and county fips from the data2add dictionary so we can add the unemployment info to the geojson.
    with open(infile, 'r') as f:
        geojson = json.load(f)
        for feature in geojson['features']:
            featureProperties = feature['properties']
            
            if year2check <= 2007:
                FIPS = featureProperties['FIPS']
                STATEFP = str(FIPS)[0:2]
                COUNTYFP = str(FIPS)[2:5]
            elif year2check <= 2009:
                STATEFP = featureProperties['STATEFP00']
                COUNTYFP = featureProperties['COUNTYFP00']
                FIPS = STATEFP + COUNTYFP
            elif year2check == 2010:
                STATEFP = featureProperties['STATEFP10']
                COUNTYFP = featureProperties['COUNTYFP10']
                FIPS = STATEFP + COUNTYFP
            elif year2check <= 2012:
                STATEFP = featureProperties['STATEFP']
                COUNTYFP = featureProperties['COUNTYFP']
                FIPS = STATEFP + COUNTYFP

            featureData = data2add.get(FIPS, {})
            for key in featureData.keys():
                featureProperties[key] = featureData[key]

    # Output this updated geojson.
    with open(outfile, 'w') as f:
        json.dump(geojson, f)
         
create_final_geojson(1970)
create_final_geojson(1980)
for year in range(1990,2018):
    create_final_geojson(year)

FileNotFoundError: [Errno 2] No such file or directory: '..\\RawData\\FinalGeoFile2000.json'

In [ ]:
if 'FIPS' in vnames:
    test = vnames.index('FIPS')
    print(test)

In [ ]:
for x in range(12):
    m = x + 1
    if m < 10:
        mm = f'0{m}'
    else:
        mm = f'{m}'
    print(f'm = {m}.  mm = {mm}')

In [ ]:
year = 2010
yr = str(year)[2:4]
print(f'yr={yr}')

In [ ]:
# to-do list
# Get the input files for other years specified
# tailor the read-in to those jsons

In [ ]:
fipsdict={}
for row, rowvals in all_county_info.iterrows():
        
    # pull information from dataframe into temporary variables
    FIPS = rowvals[0]   
    STATEFP = str(FIPS)[0:2]
    COUNTYFP = str(FIPS)[2:5]
    
    if FIPS not in fipsdict:
        fipsdict[FIPS]={}
 
    # Append the data for this county to its entry in the dictionary
    fipsdict[FIPS]={
        "STATEFP": STATEFP,
        "COUNTYFP": COUNTYFP}

fipsdict

In [ ]:
state = '12'
county='345'
fips = state + county
fips

In [ ]:
create_yearly_geojson(2000)